name: app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  flutter_svg: ^2.2.0
  cloud_firestore: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: PostNoBillsColombo
      fonts:
        - asset: fonts/post-no-bills-colombo-extrabold.ttf
          weight: 800
    - family: PorterSansBlock
      fonts:
        - asset: fonts/porter-sans-inline-block.ttf
          weight: 400